---
# VLAN sub-interface for spoke worker (Tenant B, VLAN 200)
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-tenants-worker-1
spec:
  nodeSelector:
    kubernetes.io/hostname: hcp1-worker-1
  desiredState:
    interfaces:
    - name: enp3s0.200
      type: vlan
      state: up
      vlan:
        base-iface: enp3s0
        id: 200
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: 172.16.200.64
          prefix-length: 24
      ipv6:
        enabled: false
