---
# Kustomize overlay for Lab 02: Flow tracing with tshark.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common/manifest
  - hub-capture.yaml
  - spoke-capture.yaml
