---
# Namespace for hub CUDN workloads
apiVersion: v1
kind: Namespace
metadata:
  name: cudn-hub-ns
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    cudn: hub
---
# ClusterUserDefinedNetwork for hub cluster
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: hub-network
  labels:
    advertise: "true"
spec:
  namespaceSelector:
    matchLabels:
      cudn: hub
  network:
    topology: Layer3
    layer3:
      role: Primary
      subnets:
      - cidr: 10.100.0.0/16
        hostSubnet: 24
